mode: train #[train, test]

dataset:
  dataset_name: imagenet1k_k12
  images_dir: ./data/imagenet/imagenet_1k_512
  start: 0
  images_num: 100
  regex: 'ILSVRC2012_validation_{:08d}.JPEG'
  image_paths: [] # Only activate when the dataset_name is set as "general"

model:
  model_name: GaussianImage_RS # now only support GaussianImage_RS
  init_gaussians: "net2" # [net, random, quard]
  kernel_size: 12
  init_model_path: ./checkpoints/train_init_rose-shadow-40/epoch_best.pth
  random_init:
    same_test: True # If same test is true, it will use the init net to initalize the number of gaussians, otherwise using the below "num_points".
    num_points: 20000 # number of gaussians when random initialization

train:
  iterations: 50000
  lr: 0.001
  save_path: ./output
  seed: 42
  limit_train: True
  limit_train_log_point: [2] # run only x seconds, and record psnr

wandb: # use wandb to record the training process
  activate: False
  record_iter: 2000
  project_name: "Instant-GI"